theme = "ayu_dark"


[editor]
line-number = "absolute"
mouse = false
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[keys.insert]
j = { j = "normal_mode" } # Maps `jk` to exit insert mode

